# Generated by Django 3.0.3 on 2020-03-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('unum', models.CharField(max_length=800)),
                ('ugmail', models.CharField(max_length=100)),
                ('upass', models.CharField(max_length=100)),
                ('uaddress', models.CharField(max_length=100)),
                ('ucart', models.CharField(max_length=100)),
            ],
        ),
    ]
