# Generated by Django 3.0.3 on 2020-03-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pprice', models.CharField(max_length=800)),
                ('pdes', models.CharField(max_length=100)),
                ('pp1', models.CharField(max_length=100)),
                ('pp2', models.CharField(max_length=100)),
                ('pp3', models.CharField(max_length=100)),
                ('cmt', models.CharField(max_length=200)),
            ],
        ),
    ]
