# Generated by Django 3.0.3 on 2020-03-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pp1',
            field=models.ImageField(blank=True, upload_to='product_image1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pp2',
            field=models.ImageField(blank=True, upload_to='product_image2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pp3',
            field=models.ImageField(blank=True, upload_to='product_image3'),
        ),
    ]
