# Generated by Django 3.0.3 on 2020-03-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200326_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pq',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
