# Generated by Django 3.0.3 on 2020-03-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200326_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pp1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='pp2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='pp3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
