# Generated by Django 3.0.3 on 2020-03-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200326_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdes',
            field=models.CharField(max_length=1000),
        ),
    ]
