# Generated by Django 3.0.3 on 2020-03-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200326_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cmt',
            field=models.CharField(max_length=500),
        ),
    ]
