# Generated by Django 3.0.3 on 2020-03-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200327_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=100)),
                ('productq', models.CharField(max_length=100)),
                ('unum', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=100)),
            ],
        ),
    ]
