# Generated by Django 3.0.3 on 2020-03-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ucity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='unum2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='uzip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
