# Generated by Django 3.0.3 on 2020-03-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200327_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cunum', models.CharField(max_length=100)),
                ('cpid', models.CharField(max_length=100)),
                ('cmt', models.CharField(max_length=500)),
            ],
        ),
    ]
