# Generated by Django 3.0.3 on 2020-03-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cuname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
