# Generated by Django 3.0.3 on 2020-03-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_comment_cuname'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runum', models.CharField(max_length=100)),
                ('rat', models.CharField(max_length=100)),
                ('rpid', models.CharField(max_length=100)),
            ],
        ),
    ]
