# Generated by Django 3.0.3 on 2020-04-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20200401_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='userid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
