# Generated by Django 3.0.3 on 2023-03-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_order_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='rating',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
