# Generated by Django 3.0.3 on 2023-03-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0019_auto_20230304_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cunum', models.CharField(max_length=100)),
                ('cuname', models.CharField(max_length=100, null=True)),
                ('cpid', models.CharField(max_length=100)),
                ('cmt', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=100)),
                ('productq', models.CharField(max_length=100)),
                ('unum', models.CharField(max_length=100, null=True)),
                ('uname', models.CharField(max_length=100, null=True)),
                ('txnid', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('userid', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pprice', models.CharField(max_length=800)),
                ('pdes', models.CharField(max_length=1000)),
                ('pq', models.CharField(max_length=100)),
                ('pp1', models.ImageField(null=True, upload_to='gallery/')),
                ('pp2', models.ImageField(null=True, upload_to='gallery/')),
                ('pp3', models.ImageField(null=True, upload_to='gallery/')),
                ('rate', models.CharField(max_length=200)),
                ('cmt', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runum', models.CharField(max_length=100)),
                ('rat', models.CharField(max_length=100)),
                ('rpid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('unum', models.CharField(max_length=800)),
                ('ugmail', models.CharField(max_length=100)),
                ('upass', models.CharField(max_length=100)),
                ('uaddress', models.CharField(max_length=100)),
                ('ucity', models.CharField(blank=True, max_length=100)),
                ('uzip', models.CharField(blank=True, max_length=100)),
                ('unum2', models.CharField(blank=True, max_length=100)),
                ('ucart', models.CharField(max_length=100)),
            ],
        ),
    ]
